const PIData = {
  categoryList: [
    { idx: 1, checked: false, content: "카테고리1" },
    { idx: 2, checked: false, content: "카테고리2" },
    { idx: 3, checked: false, content: "카테고리3" },
    { idx: 4, checked: false, content: "카테고리4" },
    { idx: 5, checked: false, content: "카테고리5" },
    { idx: 6, checked: false, content: "카테고리6" },
    { idx: 7, checked: false, content: "카테고리6" },
    { idx: 8, checked: false, content: "카테고리6" },
  ],
  filterTagList: [
    { idx: 1, checked: false, content: "베스트" },
    { idx: 2, checked: false, content: "베나라" },
    { idx: 3, checked: false, content: "베베" },
    { idx: 4, checked: false, content: "한우" },
    { idx: 5, checked: false, content: "뷰" },
    { idx: 6, checked: false, content: "리액트" },
    { idx: 7, checked: false, content: "앵귤러" },
    { idx: 8, checked: false, content: "여성의류" },
    { idx: 9, checked: false, content: "남성의류" },
    { idx: 10, checked: false, content: "장난감" },
    { idx: 11, checked: false, content: "홈데코" },
    { idx: 12, checked: false, content: "문구" },
    { idx: 13, checked: false, content: "취미" },
    { idx: 14, checked: false, content: "반려" },
    { idx: 15, checked: false, content: "컴퓨터" },
    { idx: 16, checked: false, content: "디지털" },
    { idx: 17, checked: false, content: "가전" },
    { idx: 18, checked: false, content: "스포츠" },
    { idx: 19, checked: false, content: "건강" },
    { idx: 20, checked: false, content: "렌탈" },
    { idx: 21, checked: false, content: "자동차" },
    { idx: 22, checked: false, content: "공구" },
    { idx: 23, checked: false, content: "여행" },
    { idx: 24, checked: false, content: "유아동" },
    { idx: 25, checked: false, content: "잡화" },
    { idx: 26, checked: false, content: "뷰티" },
    { idx: 27, checked: false, content: "도서류" },
    { idx: 28, checked: false, content: "식품" },
  ],
  product: {
    idx: "",
    category: [],
    filterTag: [],
    name: "",
    description: "",
    thumbnail: "",
    imgs: [],
    stock: "",
  },
};

export default PIData